version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: ttt_postgres
    environment:
      POSTGRES_DB: nakama
      POSTGRES_USER: nakama
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nakama -d nakama"]
      interval: 5s
      timeout: 5s
      retries: 20

  nakama:
    image: heroiclabs/nakama:3.23.1
    container_name: ttt_nakama
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./nakama.yml:/etc/nakama/nakama.yml:ro
      - ../server/bin:/nakama/data/modules
    entrypoint: ["/bin/sh", "-ecx", 
      "/nakama/nakama migrate up --database.address postgres://nakama:localdev@postgres:5432/nakama?sslmode=disable && exec /nakama/nakama --config /etc/nakama/nakama.yml --database.address postgres://nakama:localdev@postgres:5432/nakama?sslmode=disable"
    ]
    ports:
      - "7350:7350"  # gRPC
      - "7351:7351"  # Console
      - "9100:9100"  # Prometheus metrics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7351/"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  pgdata: {}
